##assuming the Samsung Data is in your working directory
x_test <- read.table("./UCI HAR Dataset/test/X_test.txt")
y_test <- read.table("./UCI HAR Dataset/test/y_test.txt")
subject_test <- read.table("./UCI HAR Dataset/test/subject_test.txt")
x_train <- read.table("./UCI HAR Dataset/train/X_train.txt")
y_train <- read.table("./UCI HAR Dataset/train/y_train.txt" )
subject_train <- read.table("./UCI HAR Dataset/train/subject_train.txt")
features <- read.table("./UCI HAR Dataset/features.txt")
#reads test data, train data, and features into data frames in R
colnames(x_test) <- features[, "V2"]
colnames(x_train) <- features[, "V2"]
##sets the elements of features as the column names for x_test and y_test
yx_test <- merge(y_test, x_test, by=0, all=TRUE)
yx_train <- merge(y_train, x_train, by = 0, all = TRUE)
##adds column of activity type to test and train data
yx_test$Row.names <- as.integer(yx_test$Row.names)
yx_train$Row.names <- as.integer(yx_train$Row.names)
##changes Row.names to integer so they can be arranged
yx_test <- arrange(yx_test, Row.names)
yx_train <- arrange(yx_train, Row.names)
##arranges by Row.names
yx_test <- rename(yx_test, activity = V1)
yx_train <- rename(yx_train, activity = V1)
##renames the second column for the activity variable
yx_test <- select(yx_test, 2:563)
yx_train <- select(yx_train, 2:563)
##removes the Row.names column but keeps all others
test_data <- merge(subject_test, yx_test, by=0, all=TRUE)
train_data <- merge(subject_train, yx_train, by=0, all=TRUE)
##adds column of subject identifier to test and train data
test_data$Row.names <- as.integer(test_data$Row.names)
train_data$Row.names <- as.integer(train_data$Row.names)
##changes Row.names to integer so they can be arranged
test_data <- arrange(test_data, Row.names)
train_data <- arrange(train_data, Row.names)
##arranges test data, and train data by Row.names
test_data <- rename(test_data, subject_id = V1)
train_data <- rename(train_data, subject_id = V1)
##renames the second column for the activity variable
test_data <- select(test_data, 2:564)
train_data <- select(train_data, 2:564)
##removes the Row.names column
test_data <- mutate(test_data, data_set = "test")
train_data <- mutate(train_data, data_set = "train")
##adds a variable to differentiate data types once they are merged
all_data <- merge(test_data, train_data, all = TRUE)
##merges train and test data sets
df <- select(all_data, matches('mean|std|subject_id|activity|data_set'))
##creates a data frame with variable names that contain any of 
##mean|std|subject_id|activity|data_set
df2 <- df[, c(1:2, 89, 3:48,52:57,61:66,70:71,73:74,76:77,79:80)]
rm(df)
##reorders column "data_set" to third column
##removes columns that are measures on meanFreq and angle as explained
##in the features_info file
walking <- filter(df2, activity == 1) %>%
  mutate(activity_type = "walking") 
walking_upstairs <- filter(df2, activity == 2) %>%
  mutate(activity_type = "walking_upstairs")
walking_downstairs <- filter(df2, activity == 3) %>%
  mutate(activity_type = "walking_downstairs")
sitting <- filter(df2, activity == 4) %>%
  mutate(activity_type = "sitting")
standing <- filter(df2, activity == 5) %>%
  mutate(activity_type = "standing")
laying <- filter(df2, activity == 6) %>%
  mutate(activity_type = "laying")
##filters by activity type and sets a descriptive name for each activity
dfa <- Reduce(function(...) merge(..., all=TRUE), list(walking, walking_upstairs, 
                                                       walking_downstairs, sitting,
                                                       standing, laying))
rm(df2, walking, walking_upstairs, walking_downstairs, sitting, standing, laying)
##simultaneously merges the filtered data frames with new descriptive 
##activity names
mydata <- dfa[, c(1, 70, 3:69)]
rm(dfa)
##reorganizes the dataframe by replacing the activity variable of numbers
##with the activity type variable that has descriptive names
##below is method for compiling data for step 5 of project
id <- filter(mydata, subject_id == 1)
  idwalking <- filter(id, activity_type == "walking")
    idwalkingmeans <- colMeans(idwalking[,4:69])
    idwalkingmeansdf <- as.data.frame(idwalkingmeans)
    idwalkingmeansdf <- t(idwalkingmeansdf)
    rm(idwalking, idwalkingmeans)
  idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
    idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
    idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
    idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
    rm(idwalking_upstairs, idwalking_upstairsmeans)
  idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
    idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
    idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
    idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
    rm(idwalking_downstairs, idwalking_downstairsmeans)
  idsitting <- filter(id, activity_type == "sitting")
    idsittingmeans <- colMeans(idsitting[,4:69])
    idsittingmeansdf <- as.data.frame(idsittingmeans)
    idsittingmeansdf <- t(idsittingmeansdf)
    rm(idsitting, idsittingmeans)
  idstanding <- filter(id, activity_type == "standing")
    idstandingmeans <- colMeans(idstanding[,4:69])
    idstandingmeansdf <- as.data.frame(idstandingmeans)
    idstandingmeansdf <- t(idstandingmeansdf)
    rm(idstanding, idstandingmeans)
  idlaying <- filter(id, activity_type == "laying")
    idlayingmeans <- colMeans(idlaying[,4:69])
    idlayingmeansdf <- as.data.frame(idlayingmeans)
    idlayingmeansdf <- t(idlayingmeansdf)
    rm(idlaying, idlayingmeans)
  id1means <- Reduce(function(...) merge(..., all=TRUE), list(
    idwalkingmeansdf, idwalking_upstairsmeansdf, 
    idwalking_downstairsmeansdf, idsittingmeansdf, 
    idstandingmeansdf, idlayingmeansdf))
  rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
  id1means <- mutate(id1means, subject_id = 1, activity_type = 1:6)
id <- filter(mydata, subject_id == 2)
  idwalking <- filter(id, activity_type == "walking")
    idwalkingmeans <- colMeans(idwalking[,4:69])
    idwalkingmeansdf <- as.data.frame(idwalkingmeans)
    idwalkingmeansdf <- t(idwalkingmeansdf)
    rm(idwalking, idwalkingmeans)
  idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
    idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
    idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
    idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
    rm(idwalking_upstairs, idwalking_upstairsmeans)
  idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
    idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
    idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
    idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
    rm(idwalking_downstairs, idwalking_downstairsmeans)
  idsitting <- filter(id, activity_type == "sitting")
    idsittingmeans <- colMeans(idsitting[,4:69])
    idsittingmeansdf <- as.data.frame(idsittingmeans)
    idsittingmeansdf <- t(idsittingmeansdf)
    rm(idsitting, idsittingmeans)
  idstanding <- filter(id, activity_type == "standing")
    idstandingmeans <- colMeans(idstanding[,4:69])
    idstandingmeansdf <- as.data.frame(idstandingmeans)
    idstandingmeansdf <- t(idstandingmeansdf)
    rm(idstanding, idstandingmeans)
  idlaying <- filter(id, activity_type == "laying")
    idlayingmeans <- colMeans(idlaying[,4:69])
    idlayingmeansdf <- as.data.frame(idlayingmeans)
    idlayingmeansdf <- t(idlayingmeansdf)
    rm(idlaying, idlayingmeans)
  id2means <- Reduce(function(...) merge(..., all=TRUE), list(
    idwalkingmeansdf, idwalking_upstairsmeansdf, 
    idwalking_downstairsmeansdf, idsittingmeansdf, 
    idstandingmeansdf, idlayingmeansdf))
  rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
  id2means <- mutate(id2means, subject_id = 2, activity_type = 1:6)
idmeans <- merge(id1means, id2means, all=TRUE)
id <- filter(mydata, subject_id == 3)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id3means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id3means <- mutate(id3means, subject_id = 3, activity_type = 1:6)
idmeans <- merge(idmeans, id3means, all=TRUE)
id <- filter(mydata, subject_id == 4)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id4means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id4means <- mutate(id4means, subject_id = 4, activity_type = 1:6)
idmeans <- merge(idmeans, id4means, all=TRUE)
id <- filter(mydata, subject_id == 5)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id5means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id5means <- mutate(id5means, subject_id = 5, activity_type = 1:6)
idmeans <- merge(idmeans, id5means, all=TRUE)
id <- filter(mydata, subject_id == 6)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id6means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id6means <- mutate(id6means, subject_id = 6, activity_type = 1:6)
idmeans <- merge(idmeans, id6means, all=TRUE)
id <- filter(mydata, subject_id == 7)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id7means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id7means <- mutate(id7means, subject_id = 7, activity_type = 1:6)
idmeans <- merge(idmeans, id7means, all=TRUE)
id <- filter(mydata, subject_id == 8)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id8means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id8means <- mutate(id8means, subject_id = 8, activity_type = 1:6)
idmeans <- merge(idmeans, id8means, all=TRUE)
id <- filter(mydata, subject_id == 9)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id9means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id9means <- mutate(id9means, subject_id = 9, activity_type = 1:6)
idmeans <- merge(idmeans, id9means, all=TRUE)
id <- filter(mydata, subject_id == 10)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id10means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id10means <- mutate(id10means, subject_id = 10, activity_type = 1:6)
idmeans <- merge(idmeans, id10means, all=TRUE)
id <- filter(mydata, subject_id == 11)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id11means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id11means <- mutate(id11means, subject_id = 11, activity_type = 1:6)
idmeans <- merge(idmeans, id11means, all=TRUE)
id <- filter(mydata, subject_id == 12)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id12means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id12means <- mutate(id12means, subject_id = 12, activity_type = 1:6)
idmeans <- merge(idmeans, id12means, all=TRUE)
id <- filter(mydata, subject_id == 13)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id13means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id13means <- mutate(id13means, subject_id = 13, activity_type = 1:6)
idmeans <- merge(idmeans, id13means, all=TRUE)
id <- filter(mydata, subject_id == 14)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id14means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id14means <- mutate(id14means, subject_id = 14, activity_type = 1:6)
idmeans <- merge(idmeans, id14means, all=TRUE)
id <- filter(mydata, subject_id == 15)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id15means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id15means <- mutate(id15means, subject_id = 15, activity_type = 1:6)
idmeans <- merge(idmeans, id15means, all=TRUE)
id <- filter(mydata, subject_id == 16)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id16means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id16means <- mutate(id16means, subject_id = 16, activity_type = 1:6)
idmeans <- merge(idmeans, id16means, all=TRUE)
id <- filter(mydata, subject_id == 17)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id17means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id17means <- mutate(id17means, subject_id = 17, activity_type = 1:6)
idmeans <- merge(idmeans, id17means, all=TRUE)
id <- filter(mydata, subject_id == 18)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id18means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id18means <- mutate(id18means, subject_id = 18, activity_type = 1:6)
idmeans <- merge(idmeans, id18means, all=TRUE)
id <- filter(mydata, subject_id == 19)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id19means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id19means <- mutate(id19means, subject_id = 19, activity_type = 1:6)
idmeans <- merge(idmeans, id19means, all=TRUE)
id <- filter(mydata, subject_id == 20)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id20means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id20means <- mutate(id20means, subject_id = 20, activity_type = 1:6)
idmeans <- merge(idmeans, id20means, all=TRUE)
id <- filter(mydata, subject_id == 21)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id21means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id21means <- mutate(id21means, subject_id = 21, activity_type = 1:6)
idmeans <- merge(idmeans, id21means, all=TRUE)
id <- filter(mydata, subject_id == 22)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id22means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id22means <- mutate(id22means, subject_id = 22, activity_type = 1:6)
idmeans <- merge(idmeans, id22means, all=TRUE)
id <- filter(mydata, subject_id == 23)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id23means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id23means <- mutate(id23means, subject_id = 23, activity_type = 1:6)
idmeans <- merge(idmeans, id23means, all=TRUE)
id <- filter(mydata, subject_id == 24)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id24means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id24means <- mutate(id24means, subject_id = 24, activity_type = 1:6)
idmeans <- merge(idmeans, id24means, all=TRUE)
id <- filter(mydata, subject_id == 25)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id25means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id25means <- mutate(id25means, subject_id = 25, activity_type = 1:6)
idmeans <- merge(idmeans, id25means, all=TRUE)
id <- filter(mydata, subject_id == 26)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id26means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id26means <- mutate(id26means, subject_id = 26, activity_type = 1:6)
idmeans <- merge(idmeans, id26means, all=TRUE)
id <- filter(mydata, subject_id == 27)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id27means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id27means <- mutate(id27means, subject_id = 27, activity_type = 1:6)
idmeans <- merge(idmeans, id27means, all=TRUE)
id <- filter(mydata, subject_id == 28)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id28means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id28means <- mutate(id28means, subject_id = 28, activity_type = 1:6)
idmeans <- merge(idmeans, id28means, all=TRUE)
id <- filter(mydata, subject_id == 29)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id29means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id29means <- mutate(id29means, subject_id = 29, activity_type = 1:6)
idmeans <- merge(idmeans, id29means, all=TRUE)
id <- filter(mydata, subject_id == 30)
idwalking <- filter(id, activity_type == "walking")
idwalkingmeans <- colMeans(idwalking[,4:69])
idwalkingmeansdf <- as.data.frame(idwalkingmeans)
idwalkingmeansdf <- t(idwalkingmeansdf)
rm(idwalking, idwalkingmeans)
idwalking_upstairs <- filter(id, activity_type == "walking_upstairs")
idwalking_upstairsmeans <- colMeans(idwalking_upstairs[,4:69])
idwalking_upstairsmeansdf <- as.data.frame(idwalking_upstairsmeans)
idwalking_upstairsmeansdf <- t(idwalking_upstairsmeansdf)
rm(idwalking_upstairs, idwalking_upstairsmeans)
idwalking_downstairs <- filter(id, activity_type == "walking_downstairs")
idwalking_downstairsmeans <- colMeans(idwalking_downstairs[,4:69])
idwalking_downstairsmeansdf <- as.data.frame(idwalking_downstairsmeans)
idwalking_downstairsmeansdf <- t(idwalking_downstairsmeansdf)
rm(idwalking_downstairs, idwalking_downstairsmeans)
idsitting <- filter(id, activity_type == "sitting")
idsittingmeans <- colMeans(idsitting[,4:69])
idsittingmeansdf <- as.data.frame(idsittingmeans)
idsittingmeansdf <- t(idsittingmeansdf)
rm(idsitting, idsittingmeans)
idstanding <- filter(id, activity_type == "standing")
idstandingmeans <- colMeans(idstanding[,4:69])
idstandingmeansdf <- as.data.frame(idstandingmeans)
idstandingmeansdf <- t(idstandingmeansdf)
rm(idstanding, idstandingmeans)
idlaying <- filter(id, activity_type == "laying")
idlayingmeans <- colMeans(idlaying[,4:69])
idlayingmeansdf <- as.data.frame(idlayingmeans)
idlayingmeansdf <- t(idlayingmeansdf)
rm(idlaying, idlayingmeans)
id30means <- Reduce(function(...) merge(..., all=TRUE), list(
  idwalkingmeansdf, idwalking_upstairsmeansdf, 
  idwalking_downstairsmeansdf, idsittingmeansdf, 
  idstandingmeansdf, idlayingmeansdf))
rm(id, idwalkingmeansdf, idwalking_upstairsmeansdf, 
   idwalking_downstairsmeansdf, idsittingmeansdf, 
   idstandingmeansdf, idlayingmeansdf)
id30means <- mutate(id30means, subject_id = 30, activity_type = 1:6)
idmeans <- merge(idmeans, id30means, all=TRUE)
rm(id1means, id2means, id3means, id4means, id5means, id6means, id7means,
   id8means, id9means, id10means, id11means, id12means, id13means, 
   id14means, id15means, id16means, id17means, id18means, id19means, 
   id20means, id21means, id22means, id23means, id24means, id25means, 
   id26means, id27means, id28means, id29means, id30means)
##very long way of getting the mean for each variable on 
##a single row for each subject for each activity
walking <- filter(idmeans, activity_type == 1) %>%
  mutate(activity = "walking") 
walking_upstairs <- filter(idmeans, activity_type == 2) %>%
  mutate(activity = "walking_upstairs")
walking_downstairs <- filter(idmeans, activity_type == 3) %>%
  mutate(activity = "walking_downstairs")
sitting <- filter(idmeans, activity_type == 4) %>%
  mutate(activity = "sitting")
standing <- filter(idmeans, activity_type == 5) %>%
  mutate(activity = "standing")
laying <- filter(idmeans, activity_type == 6) %>%
  mutate(activity = "laying")
##filters by activity type and sets a descriptive name for each activity
finaldf <- Reduce(function(...) merge(..., all=TRUE), list(walking, walking_upstairs, 
                                                       walking_downstairs, sitting,
                                                       standing, laying))
rm(idmeans, walking, walking_upstairs, walking_downstairs, sitting, standing, laying)
##simultaneously merges the filtered data frames with new descriptive 
##activity names
finaldf <- finaldf[, c(1,69,3:68)]
finaldf <- arrange(finaldf, subject_id)
